####################################
# CONFIGURATION
####################################
# Add the following variables to github secrets
#   DOCKER_REGISTRY=""
#   DOCKER_NAMESPACE="jmonkeyengine"
#   DOCKER_REGISTRY_USER="jmonkeydeploy"
#   DOCKER_REGISTRY_KEY="...." 
####################################
name: Build Environments
on:
  push:
  schedule:
  - cron: 0 0 1 * *

jobs:
  BaseImg:
    name: Build and Deploy base image
    runs-on: ubuntu-18.04     
      
    steps:    
      - name: Clone the repo
        uses: actions/checkout@v1     
        with:
          fetch-depth: 1
          
      - name: base
        run: | 
          bash ./make.sh build "buildenv-jme3" "base" "${{ secrets.DOCKER_NAMESPACE }}"
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then bash ./make.sh deploy "buildenv-jme3" "base" ${{ secrets.DOCKER_NAMESPACE }} ${{ secrets.DOCKER_REGISTRY_USER }} ${{ secrets.DOCKER_REGISTRY_KEY }} ${{ secrets.DOCKER_REGISTRY }}; fi
      
          
  LinuxArmEnv:
    needs: [BaseImg]
    name: Build and Deploy linuxArm env
    runs-on: ubuntu-18.04     
         
    steps:    
      - name: Clone the repo
        uses: actions/checkout@v1     
        with:
          fetch-depth: 1

      - name: linuxArm
        run: |  
          bash ./make.sh build "buildenv-jme3" "linuxArm" "${{ secrets.DOCKER_NAMESPACE }}"
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then bash ./make.sh deploy "buildenv-jme3" "linuxArm" ${{ secrets.DOCKER_NAMESPACE }} ${{ secrets.DOCKER_REGISTRY_USER }} ${{ secrets.DOCKER_REGISTRY_KEY }} ${{ secrets.DOCKER_REGISTRY }}; fi

  AndroidEnv:
    needs: [BaseImg]
    name: Build and Deploy android env
    runs-on: ubuntu-18.04    

    steps:    
      - name: Clone the repo
        uses: actions/checkout@v1     
        with:
          fetch-depth: 1
      - name: android
        run: |  
          bash ./make.sh build "buildenv-jme3" "android" "${{ secrets.DOCKER_NAMESPACE }}"
          if [ "$GITHUB_REF" = "refs/heads/master" ]; then bash ./make.sh deploy "buildenv-jme3" "android" ${{ secrets.DOCKER_NAMESPACE }} ${{ secrets.DOCKER_REGISTRY_USER }} ${{ secrets.DOCKER_REGISTRY_KEY }} ${{ secrets.DOCKER_REGISTRY }}; fi

  HugoEnv:
      needs: [BaseImg]
      name: Build and Deploy hugo env
      runs-on: ubuntu-18.04    

      steps:    
        - name: Clone the repo
          uses: actions/checkout@v1     
          with:
            fetch-depth: 1
        - name: hugo
          run: |  
            bash ./make.sh build "buildenv-jme3" "hugo" "${{ secrets.DOCKER_NAMESPACE }}"
            if [ "$GITHUB_REF" = "refs/heads/master" ]; then bash ./make.sh deploy "buildenv-jme3" "hugo" ${{ secrets.DOCKER_NAMESPACE }} ${{ secrets.DOCKER_REGISTRY_USER }} ${{ secrets.DOCKER_REGISTRY_KEY }} ${{ secrets.DOCKER_REGISTRY }}; fi
